package(default_visibility = ["//visibility:public"])

cc_library(
    name = "common-cxx",
    srcs = ["empty.cc"],
    hdrs = [
        "StorageConstants.hpp",
        "TupleIdSequence.hpp",
    ],
    deps = [
        "//heron/query/src/cpp/basics:basics-cxx",
    ],
    linkstatic = 1,
)
